"""adding column and gin index

Revision ID: 7b5c3711fad4
Revises: 8810637c9d2f
Create Date: 2023-12-07 20:44:59.028031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5c3711fad4'
down_revision: Union[str, None] = '8810637c9d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('new_created_column_int', sa.Integer()))

    # ### end Alembic commands ###

    op.execute(f'CREATE INDEX actor_index ON actor USING GIN(data)')
    op.execute(f'CREATE INDEX postanovka_index ON postanovka USING GIN(data)')
    op.execute(f'CREATE INDEX role_index ON role USING GIN(data)')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actor', 'new_created_column_int')    
    op.drop_index(f'actor_index', table_name='actor')
    op.drop_index(f'postanovka_index', table_name='postanovka')
    op.drop_index(f'role_index', table_name='role')

    # ### end Alembic commands ###
