"""creating tables

Revision ID: 8810637c9d2f
Revises: 
Create Date: 2023-12-07 20:44:34.287591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8810637c9d2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name_Surname', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('ampula', sa.String(length=20), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actor_Name_Surname'), 'actor', ['Name_Surname'], unique=False)
    op.create_table('postanovka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_role', sa.Date(), nullable=True),
    sa.Column('stop_role', sa.Date(), nullable=True),
    sa.Column('role_type', sa.String(length=20), nullable=True),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(length=20), nullable=False),
    sa.Column('date_of', sa.Date(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['actor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('ampula', sa.String(length=20), nullable=True),
    sa.Column('piesa', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['actor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('postanovka')
    op.drop_index(op.f('ix_actor_Name_Surname'), table_name='actor')
    op.drop_table('actor')
    # ### end Alembic commands ###
