"""adding values

Revision ID: a48dfc6ff137
Revises: 32d49c5ee830
Create Date: 2023-11-29 14:27:06.490613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a48dfc6ff137'
down_revision: Union[str, None] = '32d49c5ee830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('new_created_column_int', sa.Integer()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actor', 'new_created_column_int')

    # ### end Alembic commands ###