"""creating migration tables

Revision ID: ba0c26d1528f
Revises: 
Create Date: 2023-11-26 16:55:13.070680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0c26d1528f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_created_actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name_Surname', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('ampula', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alembic_created_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('ampula', sa.String(length=20), nullable=True),
    sa.Column('piesa', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['alembic_created_actor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_created_role')
    op.drop_table('alembic_created_actor')
    # ### end Alembic commands ###
