"""adding columns into migration tables

Revision ID: cf316b4067f6
Revises: ba0c26d1528f
Create Date: 2023-11-26 17:14:43.728074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf316b4067f6'
down_revision: Union[str, None] = 'ba0c26d1528f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alembic_created_actor', sa.Column('new_created_column_int', sa.Integer()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alembic_created_actor', 'new_created_column_int')
    # ### end Alembic commands ###
